export type PersonaDefinition = {
  slug: string;
  name: string;
  description: string;
  preferredTags: string[];
  confidenceThreshold?: "low" | "medium" | "high";
  defaultArchetype?: string;
  defaultScenario?: string;
  defaultContext?: string;
  preferredSurfaceIds?: string[];
  ignoredSurfaceIds?: string[];
  deEmphasizedSurfaceIds?: string[];
};

const adminSurfaceIds = [
  "admin-home",
  "admin-content-inbox",
  "admin-projects",
  "admin-now",
  "admin-tiny-thoughts",
  "admin-writing-drafts",
  "admin-home-spotlight",
  "admin-social-quest-log",
  "admin-context-refresh",
  "admin-guestbook",
  "admin-error-previews",
  "admin-side-hustle",
  "admin-vercel",
];

const catSurfaceIds = ["cats-beverly", "cats-thomas"];

export const personaDefinitions: PersonaDefinition[] = [
  {
    slug: "ideal-partner",
    name: "Your Ideal Partner",
    description: "A warm, curious, emotionally safe person evaluating whether the site feels grounded, interesting, and human.",
    confidenceThreshold: "low",
    defaultArchetype: "Romantic Reader",
    defaultScenario: "First visit after seeing a card, dating profile, meetup mention, or shared link.",
    defaultContext: "Evening curiosity, enough time to browse, emotionally open but cautious.",
    preferredTags: ["cats", "writing", "thoughtful", "music", "identity", "curious", "home", "signals"],
    preferredSurfaceIds: ["about", "writings", "cats-beverly", "cats-thomas", "music", "twin-peaks-self", "tiny-thoughts", "home"],
    ignoredSurfaceIds: [...adminSurfaceIds],
    deEmphasizedSurfaceIds: ["work-with-me", "build-log", "admin-vercel", "admin-context-refresh"],
  },
  {
    slug: "builder",
    name: "Builder",
    description: "A maker or technically curious creator who wants evidence that the ideas here resolve into working systems.",
    confidenceThreshold: "medium",
    defaultArchetype: "Builder",
    defaultScenario: "Evaluating ArcadeGhosts as a builder's public workbench.",
    defaultContext: "Curious, practical, and low patience for biography until the useful work appears.",
    preferredTags: ["software", "projects", "building", "ai", "workflow", "generator"],
    preferredSurfaceIds: ["work-with-me", "build-log", "search", "updates", "about", "admin-content-inbox", "admin-context-refresh", "admin-vercel"],
    ignoredSurfaceIds: [...catSurfaceIds, "movies-tv", "twin-peaks-self", "games-between-two-lodges"],
    deEmphasizedSurfaceIds: ["music", "writings", "tiny-thoughts"],
  },
  {
    slug: "creative-technologist",
    name: "Creative Technologist",
    description: "A designer-developer or digital craft person testing whether the site's personality is backed by real systems thinking.",
    confidenceThreshold: "medium",
    defaultArchetype: "Wanderer -> Builder",
    defaultScenario: "First visit after hearing about ArcadeGhosts as an unusually personal software/design experiment.",
    defaultContext: "Curious, visually alert, moderately patient, and looking for evidence that the concept has substance.",
    preferredTags: ["software", "writing", "ai", "design", "building", "projects", "curious"],
    preferredSurfaceIds: [
      "home",
      "build-log",
      "search",
      "music",
      "writings",
      "work-with-me",
      "twin-peaks-self",
      "admin-content-inbox",
      "admin-context-refresh",
      "admin-vercel",
    ],
    deEmphasizedSurfaceIds: ["movies-tv", "arcade", "games-between-two-lodges"],
  },
  {
    slug: "curious-first-date-visitor",
    name: "Curious First-Date Visitor",
    description: "A thoughtful, emotionally aware visitor trying to decide whether Jason feels warm, real, safe, and worth knowing.",
    confidenceThreshold: "medium",
    defaultArchetype: "Romantic Reader -> Scanner",
    defaultScenario: "First visit before deciding whether to continue a conversation, meet for coffee, or reply with more curiosity.",
    defaultContext: "Evening browsing, emotionally open but cautious, with enough time to explore but little patience for a maze.",
    preferredTags: ["cats", "writing", "identity", "thoughtful", "music", "home"],
    preferredSurfaceIds: ["about", "writings", "cats-beverly", "cats-thomas", "music", "tiny-thoughts", "twin-peaks-self", "home"],
    ignoredSurfaceIds: [...adminSurfaceIds],
    deEmphasizedSurfaceIds: ["work-with-me", "build-log"],
  },
  {
    slug: "fellow-programmer",
    name: "Fellow Programmer",
    description: "A technical peer looking for proof of craft, implementation depth, tradeoffs, and real shipped work.",
    confidenceThreshold: "medium",
    defaultArchetype: "Builder -> Scanner",
    defaultScenario: "Evaluating whether Jason is technically interesting enough to follow, collaborate with, hire, or talk shop with.",
    defaultContext: "Curious but skeptical, comfortable with complexity, and low patience for fluff.",
    preferredTags: ["software", "projects", "ai", "building", "workflow", "search", "architecture"],
    preferredSurfaceIds: ["work-with-me", "build-log", "search", "about", "updates", "admin-projects", "admin-context-refresh", "admin-vercel"],
    ignoredSurfaceIds: [...catSurfaceIds],
    deEmphasizedSurfaceIds: ["twin-peaks-self", "games-between-two-lodges", "movies-tv"],
  },
  {
    slug: "hiring-manager",
    name: "Hiring Manager",
    description: "A senior decision-maker evaluating whether Jason is trustworthy, capable, and professionally credible for important technical work.",
    confidenceThreshold: "medium",
    defaultArchetype: "Builder -> Hunter",
    defaultScenario: "Evaluating whether Jason should be interviewed, referred, contracted, or trusted with a leadership-level technical problem.",
    defaultContext: "Time-constrained, evidence-seeking, and open to personality only if it supports credibility.",
    preferredTags: ["software", "clear", "trust", "projects", "leadership", "work"],
    preferredSurfaceIds: ["work-with-me", "build-log", "about", "search", "updates", "home"],
    ignoredSurfaceIds: [...adminSurfaceIds, ...catSurfaceIds, "music", "twin-peaks-self", "arcade", "games-between-two-lodges"],
    deEmphasizedSurfaceIds: ["tiny-thoughts", "movies-tv"],
  },
  {
    slug: "local-coffee-bookstore-person",
    name: "Local Coffee / Bookstore Person",
    description: "A warm local visitor who wants a gentle, human sense of Jason's world more than a résumé or technical story.",
    confidenceThreshold: "low",
    defaultArchetype: "Romantic Scanner -> Reader",
    defaultScenario: "First visit after a local meeting or casual conversation.",
    defaultContext: "Relaxed but cautious, curious about the person and not the technology.",
    preferredTags: ["cats", "writing", "identity", "home", "music", "thoughtful", "warmth"],
    preferredSurfaceIds: ["about", "cats-beverly", "cats-thomas", "writings", "tiny-thoughts", "music", "home", "updates"],
    ignoredSurfaceIds: [...adminSurfaceIds],
    deEmphasizedSurfaceIds: ["work-with-me", "build-log", "search"],
  },
  {
    slug: "lonely-internet-person",
    name: "Lonely Internet Person",
    description: "A visitor looking for signs of a real human online and for a place that feels alive rather than optimized.",
    confidenceThreshold: "low",
    defaultArchetype: "Wanderer -> Reader",
    defaultScenario: "First visit while wanting connection, warmth, or a break from empty feeds.",
    defaultContext: "Late night, emotionally open, somewhat tired, and looking for signal.",
    preferredTags: ["writing", "cats", "thoughtful", "signals", "home", "identity", "community"],
    preferredSurfaceIds: ["about", "writings", "cats-beverly", "cats-thomas", "tiny-thoughts", "updates", "music", "home"],
    ignoredSurfaceIds: [...adminSurfaceIds],
    deEmphasizedSurfaceIds: ["work-with-me", "build-log", "search"],
  },
  {
    slug: "music-nerd",
    name: "Music Nerd",
    description: "A serious listener judging whether the music room rewards exploration with taste, context, and real return value.",
    confidenceThreshold: "medium",
    defaultArchetype: "Hunter -> Wanderer",
    defaultScenario: "Evaluating the music section as a listening archive and personality signal.",
    defaultContext: "Curious, opinionated, and willing to explore if the payoff is real.",
    preferredTags: ["music", "listening", "concerts", "weird", "playlist", "taste"],
    preferredSurfaceIds: ["music", "tiny-thoughts", "updates", "about", "writings", "movies-tv", "search"],
    ignoredSurfaceIds: [...adminSurfaceIds],
    deEmphasizedSurfaceIds: ["work-with-me", "build-log", ...catSurfaceIds],
  },
  {
    slug: "potential-client",
    name: "Potential Client",
    description: "Someone with a real software problem who wants competence, trust, clarity, and examples without needing to decode the whole site first.",
    confidenceThreshold: "medium",
    defaultArchetype: "Hunter -> Builder",
    defaultScenario: "Evaluating whether to start a conversation about a potential software or automation project.",
    defaultContext: "Busy, decision-heavy, under moderate time pressure, and trying to reduce risk.",
    preferredTags: ["software", "clear", "trust", "projects", "building", "automation", "ai", "search"],
    preferredSurfaceIds: ["work-with-me", "home", "build-log", "about", "search", "updates"],
    ignoredSurfaceIds: [...adminSurfaceIds, ...catSurfaceIds, "music", "twin-peaks-self", "games-between-two-lodges", "arcade", "movies-tv"],
    deEmphasizedSurfaceIds: ["tiny-thoughts", "writings", "admin-vercel"],
  },
  {
    slug: "reading-enthusiast",
    name: "Reading Enthusiast",
    description: "A thoughtful reader deciding whether the writing has enough voice, clarity, and depth to be worth lingering with.",
    confidenceThreshold: "low",
    defaultArchetype: "Reader",
    defaultScenario: "First visit focused on writing, essays, and whether the author has a voice worth following.",
    defaultContext: "Quiet attention, possibly late evening or weekend browsing.",
    preferredTags: ["writing", "thoughtful", "curiosity", "identity", "essay", "voice"],
    preferredSurfaceIds: ["writings", "writing-it-aint-over-till-its-over", "writing-my-first-cat", "about", "tiny-thoughts", "updates", "cats-beverly", "cats-thomas", "music"],
    ignoredSurfaceIds: [...adminSurfaceIds],
    deEmphasizedSurfaceIds: ["work-with-me", "build-log", "games-between-two-lodges"],
  },
  {
    slug: "retro-arcade-friend",
    name: "Retro Arcade Friend",
    description: "A playful nostalgia-minded visitor who wants the arcade rooms to feel fun, surprising, and worth wandering.",
    confidenceThreshold: "low",
    defaultArchetype: "Wanderer",
    defaultScenario: "First visit after seeing the name ArcadeGhosts or hearing that Jason likes arcades and weird little experiments.",
    defaultContext: "Playful, open, and exploratory.",
    preferredTags: ["retro", "arcades", "games", "music", "weird", "surreal", "nostalgia"],
    preferredSurfaceIds: ["arcade", "games-between-two-lodges", "home", "music", "movies-tv", "about"],
    ignoredSurfaceIds: [...adminSurfaceIds],
    deEmphasizedSurfaceIds: ["work-with-me", "build-log", "writings"],
  },
  {
    slug: "returning-fan",
    name: "Returning Fan",
    description: "A repeat visitor who already likes the site and mainly wants freshness, momentum, and reasons to keep checking back.",
    confidenceThreshold: "low",
    defaultArchetype: "RSS Subscriber -> Wanderer",
    defaultScenario: "Returning after days or weeks away.",
    defaultContext: "Moderate attention, already warm toward the site, and looking for novelty.",
    preferredTags: ["recent", "changes", "projects", "writing", "signals", "building", "freshness"],
    preferredSurfaceIds: ["updates", "build-log", "tiny-thoughts", "writings", "music", "home"],
    ignoredSurfaceIds: [...adminSurfaceIds],
    deEmphasizedSurfaceIds: ["about", "search"],
  },
  {
    slug: "rss-subscriber",
    name: "RSS Subscriber",
    description: "A visitor who wants a low-friction way to follow the site over time through feeds, updates, dates, and stable archive paths.",
    confidenceThreshold: "medium",
    defaultArchetype: "Hunter -> Reader",
    defaultScenario: "Second visit or first visit after deciding the site may be worth following.",
    defaultContext: "Focused, practical, and already mildly interested.",
    preferredTags: ["recent", "changes", "writing", "rss", "signals", "follow", "archives"],
    preferredSurfaceIds: ["updates", "writings", "tiny-thoughts", "build-log", "music", "home", "search"],
    ignoredSurfaceIds: [...adminSurfaceIds],
    deEmphasizedSurfaceIds: ["about", "arcade", "games-between-two-lodges"],
  },
  {
    slug: "skeptic",
    name: "Skeptic",
    description: "A cautious visitor testing whether the site is genuinely authored, consistent, and human rather than another polished personal brand.",
    confidenceThreshold: "high",
    defaultArchetype: "Scanner -> Reader",
    defaultScenario: "First visit after discovering ArcadeGhosts through a recommendation, GitHub project, AI discussion, business card, or social media link.",
    defaultContext: "Moderate attention, open-minded, slightly skeptical, and unwilling to waste time.",
    preferredTags: ["writing", "trust", "projects", "building", "identity", "recent", "clear"],
    preferredSurfaceIds: ["about", "writings", "build-log", "work-with-me", "tiny-thoughts", "updates", "home"],
    ignoredSurfaceIds: [...adminSurfaceIds],
    deEmphasizedSurfaceIds: ["arcade", "games-between-two-lodges", "twin-peaks-self", ...catSurfaceIds, "movies-tv"],
  },
  {
    slug: "thoughtful-introvert",
    name: "Thoughtful Introvert",
    description: "A quiet, perceptive visitor drawn to calm depth, sincerity, and interfaces that do not shout.",
    confidenceThreshold: "low",
    defaultArchetype: "Reader -> Scanner",
    defaultScenario: "First visit through writing, cats, music, or About.",
    defaultContext: "Quiet attention, low appetite for chaos, and emotionally receptive.",
    preferredTags: ["thoughtful", "writing", "cats", "home", "signals", "identity", "calm"],
    preferredSurfaceIds: ["about", "writings", "cats-beverly", "cats-thomas", "tiny-thoughts", "music", "twin-peaks-self", "home"],
    ignoredSurfaceIds: [...adminSurfaceIds],
    deEmphasizedSurfaceIds: ["work-with-me", "build-log", "movies-tv"],
  },
  {
    slug: "twin-peaks-fan",
    name: "Twin Peaks Fan",
    description: "A mood-first visitor checking whether the Twin Peaks references are emotionally real and personally meaningful rather than decorative.",
    confidenceThreshold: "medium",
    defaultArchetype: "Wanderer -> Romantic Reader",
    defaultScenario: "First visit through a Twin Peaks-related page or conversation.",
    defaultContext: "Curious, receptive, playful, and looking for mood as much as information.",
    preferredTags: ["twin", "peaks", "thoughtful", "movies", "music", "mystery", "atmosphere"],
    preferredSurfaceIds: ["twin-peaks-self", "games-between-two-lodges", "movies-tv", "music", "about", "writings", "home"],
    ignoredSurfaceIds: [...adminSurfaceIds],
    deEmphasizedSurfaceIds: ["work-with-me", "build-log"],
  },
];
